# fly.toml app configuration file generated for jhe on 2025-04-20T08:13:02-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
# Must live in the same directory as the Python manifest, requirements.txt
#

app = 'jhe'
primary_region = 'ewr'
console_command = '/code/manage.py shell'

[build]
  builder = "paketobuildpacks/builder:full"

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'
  DJANGO_LOG_LEVEL    = "INFO"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'