# Generated by Django 5.2.7 on 2025-12-15 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_clientdatasource"),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="clientdatasource",
            name="core_clientdatasource_unique_application_id_data_source_id",
        ),
        migrations.RenameField(
            model_name="clientdatasource",
            old_name="application",
            new_name="client",
        ),
        migrations.AddConstraint(
            model_name="clientdatasource",
            constraint=models.UniqueConstraint(
                fields=("client", "data_source"),
                name="core_clientdatasource_unique_client_id_data_source_id",
            ),
        ),
        migrations.AddField(
            model_name="studyclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studies",
                to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studyclient",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.study"
            ),
        ),
    ]
