# Generated by Django 5.2.7 on 2025-12-15 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_studyclient_and_more"),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="studyclient",
            constraint=models.UniqueConstraint(
                fields=("study", "client"),
                name="core_studyclient_unique_study_id_client_id",
            ),
        ),
    ]
