# Generated by Django 5.2.7 on 2026-01-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_studyclient_core_studyclient_unique_study_id_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="practitioner",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="JheSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField()),
                ("setting_id", models.IntegerField(blank=True, null=True)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("int", "Integer"),
                            ("bool", "Boolean"),
                            ("float", "Float"),
                            ("json", "Json"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value_string", models.TextField(blank=True, null=True)),
                ("value_int", models.IntegerField(blank=True, null=True)),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_float", models.FloatField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "setting_id"),
                        name="core_jhesetting_unique_key_setting_id",
                    )
                ],
            },
        ),
    ]
