# Generated by Django 5.2.7 on 2026-01-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_patient_last_updated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practitioner",
            name="birth_date",
        ),
        migrations.AlterField(
            model_name="datasource",
            name="type",
            field=models.CharField(
                choices=[
                    ("medical_device", "Medical Device"),
                    ("personal_device", "Personal Device"),
                ],
                default="personal_device",
            ),
        ),
        migrations.AlterField(
            model_name="jhesetting",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("string", "string"),
                    ("int", "int"),
                    ("bool", "bool"),
                    ("float", "float"),
                    ("json", "json"),
                ],
                max_length=10,
            ),
        ),
    ]
