# Generated by Django 6.0.3 on 2026-04-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_practitioner_birth_date_alter_datasource_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='ow_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
    ]
