# Generated by Django 6.0.4 on 2026-05-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_organization_part_of_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
